# Menu
menu:
  Home: /
  Archives: /archives
  Wiki: https://wiki.riguz.com
  Photo Gags: https://view.riguz.com
  Projects: https://bug.riguz.com
  About: /about/
  Github: https://github.com/soleverlee
rss: /atom.xml


# Miscellaneous
favicon: /images/logo.png
brand: /images/logo.png

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: true
  path: /images/ocean/
  brand: /images/logo.png

# Content
excerpt_link: Read More...
share_text: Share
search_text: Search
nav_text:
  page_prev: Prev page
  page_next: Next page
  post_prev: Newer posts
  post_next: Olde posts

# Tags
show_count: true

# Toc
toc: true

# fancybox
fancybox: true

# Gitalk
gitalk:
  enable: true # true
  clientID: 57d61245ff82e94d67b3
  clientSecret: dac16d0960bdce5d0041def03bdcf35754308431
  repo: soleverlee.github.io
  owner: soleverlee
  admin: soleverlee
