sudo: false
language: node_js
node_js:
- 16
branches:
  only:
  - master
cache: npm
addons:
  ssh_known_hosts: riguz.com
before_install:
- openssl aes-256-cbc -K $encrypted_79815f77c4c7_key -iv $encrypted_79815f77c4c7_iv
  -in deploy_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- npm install -g hexo-cli
- wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
- sudo dpkg -i ./pandoc-2.7.3-1-amd64.deb
- sudo apt-get install -y jpegoptim
- sudo apt-get install -y optipng
script:
- npm run css-build
- hexo generate --silent
- cd public/images
- ls -lh
- md5sum *
- find . -name '*.jpg' -o -name '*.jpeg' | xargs jpegoptim --strip-all
- optipng *.png
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avz --quiet --delete $TRAVIS_BUILD_DIR/public/ rsync-deploy@riguz.com:/var/www/blog
  on:
    branch: master
