sudo: false
language: node_js
node_js:
    - 8.11.3

branches:
    only:
        - master
cache: npm

before_install:
    - npm install -g hexo-cli
    - wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
    - sudo dpkg -i ./pandoc-2.7.3-1-amd64.deb
script:
    - hexo generate
deploy:
    provider: pages
    repo: solever/solever.github.io
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    on:
        branch: master
    local-dir: public