sudo: false
language: node_js
node_js:
- 8.11.3
branches:
  only:
  - master
cache: npm
addons:
  ssh_known_hosts: riguz.com
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- npm install -g hexo-cli
- wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
- sudo dpkg -i ./pandoc-2.7.3-1-amd64.deb
script:
- hexo generate
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avz --quiet --delete $TRAVIS_BUILD_DIR/public root@riguz.com:/home/www/static
  on:
    branch: master
