language: node_js

node_js:
    - 8.11.3

branches:
    only:
        - master
cache:
    directories:
        - node_modules

before_install:
    - npm install -g hexo-cli
    - echo `pwd`

install:
    - echo `pwd`
    - cd riguz.com
    - npm install

script:
    - cd riguz.com
    - hexo clean 
    - hexo generate

after_success:
    - print 'Successfully generated!'
    - cd ./public


