favicon: /images/cat_128.png
logo: /images/cat_128.png
avatar: /images/Riguz-Lee.png
copyright: 2016-2021 Riguz Lee. All rights reserved
recommended_tags:
  - tag: ~LaTeX入门
    cover: /images/LaTeX_cover.png
    description: 介绍LaTeX的一些实用用法
  - tag: ~理解Java并发
    cover: /images/OpenJDK.png
    description: JVM并发机制浅析
tag_cloud_max_count: 20

