name: Publish to blog
run-name: ${{ github.actor }} building & publishing 🚀
on:
  push:
    branches: [ master, sphinx ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build site
        run: |
          make html
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avz --quiet --delete
          path: public/
          remote_path: /var/www/blog
          remote_host: riguz.com
          remote_user: rsync-deploy
          remote_key: ${{ secrets.BLOG_PUBLISH_KEY }}